blank_issues_enabled: true
contact_links:
  - name: Question or usage help
    url: https://github.com/pablobernabeu/pilotr/discussions
    about: For questions about using pilotr, please start a discussion.
